import LoginPage from "../pages/Login";
import SignupPage from "../pages/SignupPage";
import Home from "../pages/Home";
import CreateProduct from "../pages/createProduct";
import MyProducts from "../pages/myProduct";
import Cart from "../pages/Cart";
import Profile from "../pages/profile";
import ProductDetails from "../pages/ProductDetails";
import CreateAddress from "../pages/CreateAddress";
import OrderConfirmation from "../pages/OrderConfirmation";
export {LoginPage, SignupPage, Home, CreateProduct, MyProducts, Cart, ProductDetails, Profile,CreateAddress,OrderConfirmation}; 